Completed css-two-column-layout
jdfenlason/c0321-code-solutions pull request #20
Opened 2021-03-14 15:23 UTC by jdfenlason

<img width="935" alt="Screen Shot 2021-03-14 at 11 20 37 AM" src="https://user-images.githubusercontent.com/78828085/111074042-b413a500-84b7-11eb-9c5c-3de688d70710.png">

2021-03-15 20:22 UTC, codingcodymiller requested changes
Nice work so far!! Please see my notes for detailed feedback. Additionally, your screenshot looks like the two column section is not centered in the same way as the header, please try to make sure these are consistent, and give me an updated screenshot when you have updated it.

2021-03-15 20:22 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  margin-bottom 10px;
You are missing a colon on this line

2021-03-15 20:22 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
Make sure your indenting is consistent.

2021-03-15 20:22 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +
indenting needs adjustment

2021-03-15 20:22 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +background-color: white;
indenting needs adjustment

2021-03-15 20:22 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +
Please remove empty lines in your CSS rules, with the exception of one empty line between different rules.

2021-03-16 02:52 UTC, jdfenlason commented
![Screen Shot 2021-03-15 at 10 51 12 PM](https://user-images.githubusercontent.com/78828085/111248869-26cc6f80-85e1-11eb-9a6c-24e06b6dd3d7.png)

2021-03-16 18:32 UTC, codingcodymiller approved these changes
Great work!!

2021-03-16 19:50 UTC, merged