completed javascript-primitives-and-variables
jdfenlason/c0321-code-solutions pull request #22
Opened 2021-03-15 17:57 UTC by jdfenlason

![Screen Shot 2021-03-15 at 1 53 57 PM](https://user-images.githubusercontent.com/78828085/111198808-602bbd80-8596-11eb-8e24-00164822e8e1.png)

2021-03-15 18:02 UTC, codingcodymiller requested changes
Great start! Also, please include your console logs in the code for this exercise.

2021-03-15 18:02 UTC, codingcodymiller commented on javascript-primitives-and-variables/main.js
> +var isCool = 'True';
This should be a boolean

2021-03-15 18:05 UTC, jdfenlason commented
![Screen Shot 2021-03-15 at 2 04 35 PM](https://user-images.githubusercontent.com/78828085/111199887-8aca4600-8597-11eb-9632-56bdf437b580.png)

2021-03-15 18:12 UTC, codingcodymiller requested changes
Hey man! Please include your `console.log` calls in the js file itself

2021-03-16 20:03 UTC, jdfenlason commented
![Screen Shot 2021-03-16 at 3 59 34 PM](https://user-images.githubusercontent.com/78828085/111372564-2d0a2c80-8671-11eb-992a-82c6ce744f96.png)

2021-03-16 22:17 UTC, codingcodymiller approved these changes

2021-03-16 23:28 UTC, merged