completed javascript-if
jdfenlason/c0321-code-solutions pull request #31
Opened 2021-03-17 22:58 UTC by jdfenlason

![Screen Shot 2021-03-17 at 6 53 22 PM](https://user-images.githubusercontent.com/78828085/111549472-9a41be80-8752-11eb-8ef0-a86010c083cd.png)

2021-03-17 23:13 UTC, codingcodymiller requested changes

2021-03-17 23:13 UTC, codingcodymiller commented on javascript-if/main.js
> +  }
Careful of your indentation, it starts to get pretty funky in this section.

2021-03-17 23:13 UTC, codingcodymiller commented on javascript-if/main.js
> +}
Same here, fix up this indentation

2021-03-17 23:13 UTC, codingcodymiller commented on javascript-if/main.js
> +    };
Looks like your indentation is a bit funky here too, please get this indentation to be consistent and follow proper code formatting rules.

2021-03-18 19:49 UTC, codingcodymiller requested changes
Nice work so far!! I left a note for you to address

2021-03-18 19:49 UTC, codingcodymiller commented on javascript-if/main.js
> +  if ((age) => 21) {
You have the characters backwards here. With "less than or equal to" and "greater than or equal to", the angle bracket comes first. with the equal sign first, you are using an entirely different operator we haven't talked about yet. This should be `>=`. You have this off in a couple other definitions too, double check your others while you fix this. Also, make sure you test your functions again to see if they are working as expected still

2021-03-19 00:32 UTC, jdfenlason commented
![Screen Shot 2021-03-18 at 8 23 28 PM](https://user-images.githubusercontent.com/78828085/111714870-00007a00-8829-11eb-9d17-113582807450.png)

2021-03-22 17:33 UTC, codingcodymiller approved these changes

2021-03-22 18:05 UTC, merged