Css ecommerce page
jdfenlason/c0321-code-solutions pull request #33
Opened 2021-03-18 23:49 UTC by jdfenlason

<img width="1232" alt="Screen Shot 2021-03-18 at 7 46 29 PM" src="https://user-images.githubusercontent.com/78828085/111711872-fd028b00-8822-11eb-9a7e-c6a884a812c1.png">

2021-03-19 17:56 UTC, codingcodymiller requested changes
Nice work so far! Please see my note. Additionally, only the header of your document is using the right font family, make sure you apply that font family to all text on the page. Please make sure to attach an updated screenshot once you push up your changes!

2021-03-19 17:56 UTC, codingcodymiller commented on css-ecommerce-page/styles.css
> +}
This can be removed, the link element for Google Fonts is already doing this for you.

2021-03-19 19:41 UTC, jdfenlason commented
<img width="993" alt="Screen Shot 2021-03-19 at 3 23 10 PM" src="https://user-images.githubusercontent.com/78828085/111834116-82407b00-88c9-11eb-8cb1-84dd25df4c3a.png">
I quadrupled checked to make sure it was inherited this time.  Definitely needed that exercise earlier!

2021-03-20 01:21 UTC, codingcodymiller approved these changes
Great work, man!!

2021-03-21 15:05 UTC, merged