String manipulation 2
jdfenlason/c0321-code-solutions pull request #55
Opened 2021-04-02 01:50 UTC by jdfenlason

<img width="657" alt="Screen Shot 2021-04-01 at 9 46 43 PM" src="https://user-images.githubusercontent.com/78828085/113371394-36172100-9334-11eb-9bc3-4bbd83f67bb1.png">

2021-04-05 17:42 UTC, codingcodymiller requested changes
Great start!! A couple notes for you, here

2021-04-05 17:42 UTC, codingcodymiller commented on string-manipulation-2/src/capitalize-words.js
> +  return capWords.slice(0, capWords.length - 1);
Instead of concatenation, why not create an array to hold the capitalized words, then `join` them after the loop ends?

2021-04-05 17:42 UTC, codingcodymiller commented on string-manipulation-2/src/num-vowels.js
> +    var capLetter = string[i].toLowerCase();
`capLetter` that hold a lowercase letter? Unless this letter is secretly Captain America, this variable seems to be misnamed.

2021-04-05 17:42 UTC, codingcodymiller commented on string-manipulation-2/src/truncate.js
> +  }
What is your `for` loop doing for you here?

2021-04-06 00:58 UTC, jdfenlason commented
![Screen Shot 2021-04-05 at 7 02 03 PM](https://user-images.githubusercontent.com/78828085/113644006-b221a980-9651-11eb-8e1e-f809ac95961a.png)

2021-04-06 00:59 UTC, jdfenlason commented
![Screen Shot 2021-04-05 at 8 56 41 PM](https://user-images.githubusercontent.com/78828085/113644026-c2398900-9651-11eb-96fa-ffc5cc0ed140.png)

2021-04-06 16:46 UTC, codingcodymiller approved these changes

2021-04-06 16:46 UTC, merged