Completed array-manipulation-3
jdfenlason/c0321-code-solutions pull request #59
Opened 2021-04-04 14:42 UTC by jdfenlason

![Screen Shot 2021-04-04 at 10 39 53 AM](https://user-images.githubusercontent.com/78828085/113512397-7512c580-9532-11eb-99bd-2d8b991c0d9d.png)

2021-04-06 17:07 UTC, codingcodymiller requested changes

2021-04-06 17:07 UTC, codingcodymiller commented on array-manipulation-3/src/zip.js
> +  } else if (first.length > second.length) {
This can just be an `else`. If the lengths aren't equal or `first` isn't less than `second`, then the length of `second` _is_ greater than `first`

2021-04-06 17:07 UTC, codingcodymiller commented on array-manipulation-3/src/zip.js
> +  if (first.length === second.length || first.length < second.length) {
Why not just `<=`?

2021-04-07 20:03 UTC, jdfenlason commented
![Screen Shot 2021-04-07 at 4 02 05 PM](https://user-images.githubusercontent.com/78828085/113926929-d056e900-97ba-11eb-826b-76320fee4249.png)

2021-04-07 21:58 UTC, scbowler approved these changes
Great job implementing Cody's feedback, looks good! 👍

2021-04-07 22:14 UTC, merged